apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: chatbot
    tier: backend
    service: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: chatbot
    tier: backend
    service: redis
