apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: chatbot
      tier: backend
      service: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: chatbot
        tier: backend
        service: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.3-alpine
        ports:
        - containerPort: 6379
